### ISSUE TITLE
Reviewing the Pika.py DMP - team Playarists

### ISSUE THREAD

**Issue by essepuntato** [open-sci/2022-2023#10]
Hi @open-sci/playarists,

As anticipated in the [lectures on Wednesday](https://docs.google.com/presentation/d/1Y6CdDwgcuQpRJBDbSDDbDBXULCWljCGSnsgn_FU0hPs/edit#slide=id.gd0ba9f17f0_0_142), one of you have to review the [DMP developed by the team Pika.py](https://github.com/open-sci/2022-2023/issues/5). The person selected for addressing this task must work independently to write a review and publish it on [Qeios](https://www.qeios.com/) to get a DOI for it. A reminder: once the review is published and a DOI is obtained, the review cannot be modified anymore.

Once both your reviews are published, close this issue by attaching in the comment the clickable DOI URLs (https://doi.org/...) of both reviews.

If you have any more questions, please don't hesitate to contact me in the Slack group.

**Comment by ghasempouri1984** [comment]
https://doi.org/10.32388/7CLRJX
