### ISSUE TITLE
Submitting the software - team Pika.py

### ISSUE THREAD

**Issue by essepuntato** [open-sci/2022-2023#18]
Hi @open-sci/pika-py,

As anticipated in [one of the previous lectures](https://docs.google.com/presentation/d/1LHPGt18AhFF-VkzQljlsiADWCnWvzy-I6ZoMDNtJMqo/edit#slide=id.gcd92ad6878_0_3), once finalised, the [software you developed](https://github.com/open-sci/2022-2023-pika-py-code) must be assigned with a DOI via Zenodo.

Once in Zenodo, close this issue by attaching in the comment the clickable DOI URL (https://doi.org/...) of the software. The version specified here must also be the one cited in the research article to write.

Do not hesitate to contact me in the Slack group for further doubts.

**Comment by olgagolgan** [comment]
https://doi.org/10.5281/zenodo.7978742
