### ISSUE TITLE
First version of the protocol - team Pika.py

### ISSUE THREAD

**Issue by essepuntato** [open-sci/2022-2023#7]
Hi @open-sci/pika-py,

As anticipated in [one of the previous lectures](https://docs.google.com/presentation/d/1ODujBmeKCJmIBqZlzVBPioU_LPYaospnKs7CxQ0W_Ww/edit?usp=sharing), you have to create the first version of your workflow using [Protocols.io](https://protocols.io/).

The workflow should describe how you will address the research question related to your project. In particular, you
should focus on the steps to produce your output data (including explicit mentions of existing data and methods reused) and how these will be then analysed (e.g. by indicating which statistical tool or visualisation you will adopt) to answer your research question.

Once your first version of the workflow is finalised, please publish it using the Protocols.io interface. Then, close this issue by attaching in the comment the clickable DOI URL (https://doi.org/...) of the first version of the workflow.

For further doubts, do not hesitate to contact me in the Slack group.

**Comment by olgagolgan** [comment]
https://doi.org/10.17504/protocols.io.n92ldpeenl5b/v1
the DOI is currently not working because the protocol is in the publication phase, which should be finished in a couple of days.
