### ISSUE TITLE
Reviewing the Playarists DMP - team Pika.py

### ISSUE THREAD

**Issue by essepuntato** [open-sci/2022-2023#9]
Hi @open-sci/pika-py,

As anticipated in the [lectures on Wednesday](https://docs.google.com/presentation/d/1Y6CdDwgcuQpRJBDbSDDbDBXULCWljCGSnsgn_FU0hPs/edit#slide=id.gd0ba9f17f0_0_142), two of you have to review the [DMP developed by the team Playarists](https://github.com/open-sci/2022-2023/issues/6). The two people selected for addressing this task must work independently to write a review and publish it on [Qeios](https://www.qeios.com/) to get a DOI for it. A reminder: once the review is published and a DOI is obtained, the review cannot be modified anymore.

Once both your reviews are published, close this issue by attaching in the comment the clickable DOI URLs (https://doi.org/...) of both reviews.

If you have any more questions, please don't hesitate to contact me in the Slack group.

**Comment by Postitisnt** [comment]
https://www.qeios.com/read/TBDDN0

**Comment by SaraVell1** [comment]
https://doi.org/10.32388/LRYCBA

**Comment by Postitisnt** [comment]
https://doi.org/10.32388/TBDDN0
